{
 "title": "EC2 Monitoring",
 "tags": [
  "Autoscaling",
  "EC2",
  "AWS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "region", "label": "region", "query": "regions()" },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "deployment_id",
    "label": "deployment_id",
    "query": "ec2_instance_attribute(us-east-1, Tags.deployment_id, { })"
   },
   {
    "name": "cvt_autoscaling",
    "label": "cvt_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"cvt\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "cvt_misc_autoscaling",
    "label": "cvt_misc_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"cvt_misc\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "mps_autoscaling",
    "label": "mps_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"mps_processor\"], \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "camera_autoscaling",
    "label": "camera_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"camera\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "dxt_autoscaling",
    "label": "dxt_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"dxt\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "fd19_flink_autoscaling",
    "label": "fd19_flink_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"fd19_flink\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "fd19_validation_autoscaling",
    "label": "fd19_validation_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"fd19_validation\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "stream_analytic_autoscaling",
    "label": "stream_analytic_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"stream_analytics\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "decode_autoscaling",
    "label": "decode_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"decode\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "localization_autoscaling",
    "label": "localization_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"localization\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "multiview_autoscaling",
    "label": "multiview_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"multiview\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "render_hd_autoscaling",
    "label": "render_hd_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"render_hd\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "segmentation_autoscaling",
    "label": "segmentation_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:k8s.io/cluster-autoscaler/node-template/label/cluster\": [\"segmentation\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   },
   {
    "name": "logstash_autoscaling",
    "label": "logstash_autoscaling",
    "query": "ec2_instance_attribute($region, Tags.aws:autoscaling:groupName, {\"tag:Name\": [\"k8s_logstash\"],  \"tag:deployment_id\": [\"$datasource\"]})"
   }
  ]
 },
 "panels": [
  { "title": "LOGSTASH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "repeat": "logstash_autoscaling",
   "content": "\n#### **$logstash_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "repeat": "logstash_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$logstash_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "repeat": "logstash_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$logstash_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "repeat": "logstash_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$logstash_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "repeat": "logstash_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$logstash_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "repeat": "logstash_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$logstash_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "repeat": "logstash_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$logstash_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "repeat": "logstash_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$logstash_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "SEGMENTATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "repeat": "segmentation_autoscaling",
   "content": "\n#### **$segmentation_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "repeat": "segmentation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$segmentation_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "repeat": "segmentation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$segmentation_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 5 },
   "repeat": "segmentation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$segmentation_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 5 },
   "repeat": "segmentation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$segmentation_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 5 },
   "repeat": "segmentation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$segmentation_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 5 },
   "repeat": "segmentation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$segmentation_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "repeat": "segmentation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$segmentation_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "RENDER-HD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
   "repeat": "render_hd_autoscaling",
   "content": "\n#### **$render_hd_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 9 },
   "repeat": "render_hd_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$render_hd_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 9 },
   "repeat": "render_hd_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$render_hd_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 9 },
   "repeat": "render_hd_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$render_hd_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 9 },
   "repeat": "render_hd_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$render_hd_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 9 },
   "repeat": "render_hd_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$render_hd_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 9 },
   "repeat": "render_hd_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$render_hd_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "repeat": "render_hd_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$render_hd_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "MULTIVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 13 },
   "repeat": "multiview_autoscaling",
   "content": "\n#### **$multiview_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 13 },
   "repeat": "multiview_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$multiview_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 13 },
   "repeat": "multiview_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$multiview_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 13 },
   "repeat": "multiview_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$multiview_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 13 },
   "repeat": "multiview_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$multiview_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 13 },
   "repeat": "multiview_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$multiview_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 13 },
   "repeat": "multiview_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$multiview_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "repeat": "multiview_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$multiview_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "LOCALIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 17 },
   "repeat": "localization_autoscaling",
   "content": "\n#### **$localization_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 17 },
   "repeat": "localization_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$localization_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 17 },
   "repeat": "localization_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$localization_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 17 },
   "repeat": "localization_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$localization_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 17 },
   "repeat": "localization_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$localization_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 17 },
   "repeat": "localization_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$localization_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 17 },
   "repeat": "localization_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$localization_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "repeat": "localization_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$localization_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "DECODE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 21 },
   "repeat": "decode_autoscaling",
   "content": "\n#### **$decode_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 21 },
   "repeat": "decode_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$decode_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 21 },
   "repeat": "decode_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$decode_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 21 },
   "repeat": "decode_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$decode_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 21 },
   "repeat": "decode_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$decode_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 21 },
   "repeat": "decode_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$decode_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 21 },
   "repeat": "decode_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$decode_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "repeat": "decode_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$decode_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "STREAM-ANALYTICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 25 },
   "repeat": "stream_analytic_autoscaling",
   "content": "\n#### **$stream_analytic_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 25 },
   "repeat": "stream_analytic_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$stream_analytic_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 25 },
   "repeat": "stream_analytic_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$stream_analytic_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 25 },
   "repeat": "stream_analytic_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$stream_analytic_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 25 },
   "repeat": "stream_analytic_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$stream_analytic_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 25 },
   "repeat": "stream_analytic_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$stream_analytic_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 25 },
   "repeat": "stream_analytic_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$stream_analytic_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "repeat": "stream_analytic_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$stream_analytic_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "FD19-VALIDATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 29 },
   "repeat": "fd19_validation_autoscaling",
   "content": "\n#### **$fd19_validation_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 29 },
   "repeat": "fd19_validation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$fd19_validation_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 29 },
   "repeat": "fd19_validation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_validation_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 29 },
   "repeat": "fd19_validation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_validation_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 29 },
   "repeat": "fd19_validation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_validation_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 29 },
   "repeat": "fd19_validation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_validation_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 29 },
   "repeat": "fd19_validation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_validation_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "repeat": "fd19_validation_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$fd19_validation_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "FD19-FLINK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 33 },
   "repeat": "fd19_flink_autoscaling",
   "content": "\n#### **$fd19_flink_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 33 },
   "repeat": "fd19_flink_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$fd19_flink_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 33 },
   "repeat": "fd19_flink_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_flink_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 33 },
   "repeat": "fd19_flink_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_flink_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 33 },
   "repeat": "fd19_flink_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_flink_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 33 },
   "repeat": "fd19_flink_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_flink_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 33 },
   "repeat": "fd19_flink_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$fd19_flink_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 33 },
   "repeat": "fd19_flink_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$fd19_flink_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "DXT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 37 },
   "repeat": "dxt_autoscaling",
   "content": "\n#### **$dxt_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 37 },
   "repeat": "dxt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$dxt_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 37 },
   "repeat": "dxt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$dxt_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 37 },
   "repeat": "dxt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$dxt_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 37 },
   "repeat": "dxt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$dxt_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 37 },
   "repeat": "dxt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$dxt_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 37 },
   "repeat": "dxt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$dxt_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 37 },
   "repeat": "dxt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$dxt_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "CAMERA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 41 },
   "repeat": "camera_autoscaling",
   "content": "\n#### **$camera_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 41 },
   "repeat": "camera_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$camera_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 41 },
   "repeat": "camera_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$camera_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 41 },
   "repeat": "camera_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$camera_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 41 },
   "repeat": "camera_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$camera_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 41 },
   "repeat": "camera_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$camera_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 41 },
   "repeat": "camera_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$camera_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 41 },
   "repeat": "camera_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$camera_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "MPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 45 },
   "repeat": "mps_autoscaling",
   "content": "\n#### **$mps_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 45 },
   "repeat": "mps_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$mps_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 45 },
   "repeat": "mps_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$mps_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 45 },
   "repeat": "mps_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$mps_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 45 },
   "repeat": "mps_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$mps_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 45 },
   "repeat": "mps_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$mps_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 45 },
   "repeat": "mps_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$mps_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 45 },
   "repeat": "mps_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$mps_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "CVT_MISC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 49 },
   "repeat": "cvt_misc_autoscaling",
   "content": "\n#### **$cvt_misc_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 49 },
   "repeat": "cvt_misc_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$cvt_misc_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 49 },
   "repeat": "cvt_misc_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_misc_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 49 },
   "repeat": "cvt_misc_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_misc_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 49 },
   "repeat": "cvt_misc_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_misc_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 49 },
   "repeat": "cvt_misc_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_misc_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 49 },
   "repeat": "cvt_misc_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_misc_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 49 },
   "repeat": "cvt_misc_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$cvt_misc_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "CVT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 53 },
   "repeat": "cvt_autoscaling",
   "content": "\n#### **$cvt_autoscaling**\n\n\n\n\n\n",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Current Total Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 53 },
   "repeat": "cvt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$cvt_autoscaling" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 53 },
   "repeat": "cvt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_autoscaling" },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MinSize",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 53 },
   "repeat": "cvt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_autoscaling" },
     "metricName": "GroupMinSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Max Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 53 },
   "repeat": "cvt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_autoscaling" },
     "metricName": "GroupMaxSize",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 53 },
   "repeat": "cvt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_autoscaling" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 53 },
   "repeat": "cvt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cvt_autoscaling" },
     "metricName": "GroupPendingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 53 },
   "repeat": "cvt_autoscaling",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "AutoScalingGroupName": "$cvt_autoscaling" },
     "metricName": "GroupTerminatingInstances",
     "namespace": "AWS/AutoScaling",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}