{
 "title": "Monitoring Infrastructure",
 "tags": [
  "Influxdb",
  "kds agent",
  "fd19-stream-analytics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "fd19Deployments", "label": "fd19-deployments", "query": "prometheus" },
   {
    "name": "daemonset",
    "label": "daemonset",
    "query": "label_values(kube_daemonset_created, daemonset)"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "deployment", "label": "deployment", "query": "label_values(deployment)" }
  ]
 },
 "panels": [
  {
   "title": "Influxdb CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\".*influxd.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Influxdb Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\".*influxd.*$\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Influxdb network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"^.*influxd.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name, kubernetes_io_hostname)",
     "legendFormat": "receive-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"^.*influxd.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name, kubernetes_io_hostname)",
     "legendFormat": "transmit<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Influxdb Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (kubelet_volume_stats_used_bytes{kubernetes_io_hostname=~\"^$Node$\", persistentvolumeclaim=~\"^.*influx.*$\"} / kubelet_volume_stats_capacity_bytes{kubernetes_io_hostname=~\"^$Node$\", persistentvolumeclaim=~\"^.*influx.*$\"})",
     "legendFormat": "{{ persistentvolumeclaim }} "
    }
   ]
  },
  {
   "title": "fd19-stream-analytics-tm CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\"^fd19-stream-analytics-tm.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "fd19-stream-analytics-tm Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\"fd19-stream-analytics-tm.*$\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "fd19-stream-analytics-jm Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\"fd19-stream-analytics-jm.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "fd19-stream-analytics-jm Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\"fd19-stream-analytics-jm.*$\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "kds-agent Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\"kds-agent.*$\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name,kubernetes_io_hostname)"
    },
    {
     "expr": "sum ((kube_pod_container_resource_requests_memory_bytes{pod=~\"kds-agent.*$\",node=~\"^$Node$\"})) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    },
    {
     "expr": "sum ((kube_node_status_allocatable_memory_bytes{node=~\"^$Node$\"})) by (node)",
     "legendFormat": "avlbl: {{ node }}"
    }
   ]
  },
  {
   "title": "kds-agent CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\"kds-agent.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name,kubernetes_io_hostname)"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod=~\"kds-agent.*$\",node=~\"^$Node$\"}) by (pod,node)"
    },
    {
     "expr": "sum ((kube_node_status_allocatable_cpu_cores{node=~\"^$Node$\"})) by (node)"
    }
   ]
  }
 ]
}